-- Core records used by the invoice matching and review workflow.
-- Run against PostgreSQL; IDs are generated locally and timestamps use UTC.

CREATE TABLE IF NOT EXISTS vendor (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            TEXT NOT NULL,
    normalized_name TEXT NOT NULL,
    tax_id          TEXT,
    email           TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS vendor_normalized_name_uq
    ON vendor (normalized_name);
CREATE INDEX IF NOT EXISTS vendor_tax_id_idx ON vendor (tax_id);

-- One row represents one PO line item. A PO with multiple items has multiple rows.
CREATE TABLE IF NOT EXISTS po (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id   BIGINT NOT NULL REFERENCES vendor(id),
    item        TEXT NOT NULL,
    amount      NUMERIC(14, 2) NOT NULL CHECK (amount >= 0),
    qty         NUMERIC(14, 3) NOT NULL CHECK (qty >= 0),
    status      TEXT NOT NULL DEFAULT 'open'
                CHECK (status IN ('open', 'partially_received', 'received', 'closed', 'cancelled')),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS po_vendor_id_idx ON po (vendor_id);

CREATE TABLE IF NOT EXISTS goods_receipt (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_id       BIGINT NOT NULL REFERENCES po(id),
    qty         NUMERIC(14, 3) NOT NULL CHECK (qty >= 0),
    received_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    detail      JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS goods_receipt_po_id_idx ON goods_receipt (po_id);

CREATE TABLE IF NOT EXISTS invoice (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id       BIGINT REFERENCES vendor(id),
    po_id           BIGINT REFERENCES po(id),
    file_hash       TEXT NOT NULL UNIQUE,
    invoice_number  TEXT,
    invoice_date    DATE,
    due_date        DATE,
    currency        CHAR(3),
    total_amount    NUMERIC(14, 2) CHECK (total_amount IS NULL OR total_amount >= 0),
    extracted_fields JSONB NOT NULL DEFAULT '{}'::jsonb,
    extraction_confidence NUMERIC(5, 4)
                      CHECK (extraction_confidence IS NULL OR extraction_confidence BETWEEN 0 AND 1),
    status          TEXT NOT NULL DEFAULT 'received'
                    CHECK (status IN ('received', 'processing', 'pending_review', 'approved', 'rejected', 'posted', 'failed')),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS invoice_vendor_id_idx ON invoice (vendor_id);
CREATE INDEX IF NOT EXISTS invoice_po_id_idx ON invoice (po_id);
CREATE INDEX IF NOT EXISTS invoice_status_idx ON invoice (status);

CREATE TABLE IF NOT EXISTS review_task (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id    BIGINT NOT NULL REFERENCES invoice(id),
    status        TEXT NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending', 'approved', 'rejected')),
    reviewer_notes TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    reviewed_at   TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS review_task_status_idx ON review_task (status);
CREATE INDEX IF NOT EXISTS review_task_invoice_id_idx ON review_task (invoice_id);

CREATE TABLE IF NOT EXISTS erp_posted (
    invoice_id      BIGINT PRIMARY KEY REFERENCES invoice(id),
    idempotency_key TEXT NOT NULL UNIQUE,
    posted_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id  BIGINT REFERENCES invoice(id),
    event       TEXT NOT NULL,
    timestamp   TIMESTAMPTZ NOT NULL DEFAULT now(),
    detail      JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX IF NOT EXISTS audit_log_invoice_timestamp_idx
    ON audit_log (invoice_id, timestamp DESC);
