[project]
name = "invoice-exception-agent-langgraph-architecture"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Abhigyan Dey", email = "abhigyandey2@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
invoice-exception-agent-langgraph-architecture = "invoice_exception_agent_langgraph_architecture:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
